layout_spectrum: 0
typography_spectrum: 0.06989247
color:
  saturation: 0.9266831
  lightness: 0.7878734
  brandStrength: 0.7724015
  brandColors:
    - '#FFFFFF'
    - '#020202'
    - '#CFCFCF'
    - '#303030'
    - '#5C5C5C'
  rhythmicContrast: 0.9344939
name: Doodle on Your Stuff
